import type { Product, Promotion, User, Chef } from './types';

export const products: Product[] = [
  {
    id: 'prod-001',
    name: 'Classic Croissant',
    type: 'pastry',
    price: 3.5,
    imageUrl: 'https://picsum.photos/seed/101/600/400',
    imageHint: 'croissant pastry',
    description: {
      en: 'A buttery, flaky, viennoiserie pastry of Austrian origin, named for its historical crescent shape.',
      es: 'Un pastel de hojaldre mantecoso y escamoso de origen austriaco, llamado así por su histórica forma de media luna.',
    },
    ingredients: ['Flour', 'Butter', 'Yeast', 'Sugar', 'Salt'],
    chefId: 'chef-001',
    preparationTime: 24,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: false,
      isDairyFree: false,
      isNutFree: true,
    },
  },
  {
    id: 'prod-002',
    name: 'Chocolate Eclair',
    type: 'dessert',
    price: 4.5,
    imageUrl: 'https://picsum.photos/seed/102/600/400',
    imageHint: 'chocolate eclair',
    description: {
      en: 'A cream-filled oblong pastry with a rich chocolate topping.',
      es: 'Un pastelito oblongo relleno de crema con una rica cobertura de chocolate.',
    },
    ingredients: ['Flour', 'Eggs', 'Cream', 'Chocolate', 'Sugar'],
    chefId: 'chef-001',
    preparationTime: 8,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: false,
      isDairyFree: false,
      isNutFree: true,
    },
  },
  {
    id: 'prod-003',
    name: 'Artisanal Sourdough',
    type: 'savory',
    price: 8.0,
    imageUrl: 'https://picsum.photos/seed/103/600/400',
    imageHint: 'sourdough bread',
    description: {
      en: 'A rustic loaf with a tangy flavor, crisp crust, and soft, chewy interior.',
      es: 'Un pan rústico con un sabor ácido, corteza crujiente e interior suave y masticable.',
    },
    ingredients: ['Sourdough Starter', 'Flour', 'Water', 'Salt'],
    chefId: 'chef-002',
    preparationTime: 48,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: true,
      isDairyFree: true,
      isNutFree: true,
    },
  },
  {
    id: 'prod-004',
    name: 'Assorted Macarons',
    type: 'dessert',
    price: 12.0,
    imageUrl: 'https://picsum.photos/seed/104/600/400',
    imageHint: 'macarons assortment',
    description: {
      en: 'A box of six colorful French macarons with various fillings.',
      es: 'Una caja de seis coloridos macarons franceses con varios rellenos.',
    },
    ingredients: ['Almond Flour', 'Sugar', 'Egg Whites', 'Ganache'],
    chefId: 'chef-001',
    preparationTime: 12,
    dietaryFlags: {
      isGlutenFree: true,
      isVegan: false,
      isDairyFree: false,
      isNutFree: false,
    },
  },
  {
    id: 'prod-005',
    name: 'Fudgy Vegan Brownie',
    type: 'dessert',
    price: 5.0,
    imageUrl: 'https://picsum.photos/seed/105/600/400',
    imageHint: 'vegan brownie',
    description: {
      en: 'A deliciously rich and fudgy chocolate brownie, completely plant-based.',
      es: 'Un brownie de chocolate deliciosamente rico y fudgy, completamente a base de plantas.',
    },
    ingredients: ['Flour', 'Cocoa Powder', 'Vegan Butter', 'Flax Eggs', 'Sugar'],
    chefId: 'chef-002',
    preparationTime: 4,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: true,
      isDairyFree: true,
      isNutFree: true,
    },
  },
  {
    id: 'prod-006',
    name: 'Quiche Lorraine',
    type: 'savory',
    price: 7.5,
    imageUrl: 'https://picsum.photos/seed/106/600/400',
    imageHint: 'quiche lorraine',
    description: {
      en: 'A classic savory tart with a rich filling of bacon, eggs, and cream.',
      es: 'Una clásica tarta salada con un rico relleno de tocino, huevos y crema.',
    },
    ingredients: ['Pastry Crust', 'Bacon', 'Eggs', 'Cream', 'Gruyere Cheese'],
    chefId: 'chef-001',
    preparationTime: 6,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: false,
      isDairyFree: false,
      isNutFree: true,
    },
  },
  {
    id: 'prod-007',
    name: 'Gluten-Free Cupcakes',
    type: 'dessert',
    price: 4.0,
    imageUrl: 'https://picsum.photos/seed/107/600/400',
    imageHint: 'cupcakes',
    description: {
      en: 'Light and fluffy vanilla cupcakes made with gluten-free flour.',
      es: 'Cupcakes de vainilla ligeros y esponjosos hechos con harina sin gluten.',
    },
    ingredients: ['Gluten-Free Flour Blend', 'Sugar', 'Eggs', 'Butter', 'Vanilla'],
    chefId: 'chef-002',
    preparationTime: 3,
    dietaryFlags: {
      isGlutenFree: true,
      isVegan: false,
      isDairyFree: false,
      isNutFree: true,
    },
  },
  {
    id: 'prod-008',
    name: 'Spinach Feta Turnover',
    type: 'savory',
    price: 6.0,
    imageUrl: 'https://picsum.photos/seed/109/600/400',
    imageHint: 'savory pastry',
    description: {
      en: 'Flaky puff pastry filled with a savory mixture of spinach and feta cheese.',
      es: 'Hojaldre escamoso relleno de una mezcla salada de espinacas y queso feta.',
    },
    ingredients: ['Puff Pastry', 'Spinach', 'Feta Cheese', 'Onion', 'Herbs'],
    chefId: 'chef-002',
    preparationTime: 4,
    dietaryFlags: {
      isGlutenFree: false,
      isVegan: false,
      isDairyFree: false,
      isNutFree: true,
    },
  },
];

export const promotions: Promotion[] = [
  {
    id: 'promo-001',
    title: {
      en: 'Weekend Pastry Special!',
      es: '¡Especial de Repostería de Fin de Semana!',
    },
    description: {
      en: 'Get 15% off all pastries this weekend!',
      es: '¡Obtén un 15% de descuento en toda la repostería este fin de semana!',
    },
    imageUrl: 'https://picsum.photos/seed/201/1200/400',
    imageHint: 'bakery display',
    discountPercentage: 15,
  },
  {
    id: 'promo-002',
    title: {
      en: 'Try Our New Savory Items',
      es: 'Prueba Nuestros Nuevos Platos Salados',
    },
    description: {
      en: 'Buy any savory item, get a free croissant!',
      es: '¡Compra cualquier plato salado y llévate un croissant gratis!',
    },
    imageUrl: 'https://picsum.photos/seed/202/1200/400',
    imageHint: 'savory food',
    freeItem: 'prod-001',
  },
];

export const sampleUser: User = {
  id: 'user-001',
  name: 'Alex Doe',
  email: 'alex.doe@example.com',
  phone: '555-123-4567',
  profilePictureUrl: 'https://picsum.photos/seed/301/100/100',
  imageHint: 'person portrait',
  address: {
    street: '123 Main St',
    city: 'Foodville',
    state: 'CA',
    zip: '90210',
    country: 'USA',
  },
};

export const sampleChef: Chef = {
  id: 'chef-001',
  name: 'Julia Pastry',
  email: 'julia.p@tastyapp.com',
  profilePictureUrl: 'https://picsum.photos/seed/302/100/100',
  imageHint: 'chef cooking',
  gender: 'female',
};
